data-analyzer:
  build: ./data-analyzer
  volumes:
    - ./results:/tmp/results
  ports:
    - "8175:8175"
tester:
  build: ./tester
  links:
    - data-analyzer
  volumes:
    - ./results:/tmp/results
